# Generated by Django 3.2.5 on 2021-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tlfno',
            field=models.CharField(max_length=8, verbose_name='El teléfono'),
        ),
    ]
